version: '3.8'

services:
  catalogdb:
    image: postgres:18
    container_name: catalogdb
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: qwerr112358
      POSTGRES_DB: CatalogDb
    volumes:
      - postgres_catalog:/var/lib/postgresql

volumes:
  postgres_catalog:
